### ISSUE TITLE
Empty subscription list causes Out of Memory error

### ISSUE THREAD

**Issue by DavidAntliff** [SpotlightKid/osc2mqtt#3]
In my application I have no need to translate MQTT messages into OSC messages (all communication is one-way, OSC to MQTT). However the default seems to be to subscribe to "#" which receives all published messages.

I attempted to disable this by setting:

`subscriptions = `

However this causes:

```
$ osc2mqtt -v
INFO:osc2mqtt:Connecting to MQTT broker localhost:1883 ...
DEBUG:osc2mqtt:Starting MQTT thread...
INFO:osc2mqtt:Starting OSC server listening on port 9001 ...
DEBUG:osc2mqtt:MQTT connect: Connection Accepted.
DEBUG:osc2mqtt:MQTT disconnect: Out of memory.
DEBUG:osc2mqtt:MQTT connect: Connection Accepted.
DEBUG:osc2mqtt:MQTT disconnect: Out of memory.
```

As an alternative, I tried simply commenting out the `subscriptions` line, but that seems to pick up a default (maybe "#" again?) and shows unhandled MQTT messages arriving in the `-v` log.

For now, I set `subscriptions = dummy` to avoid this issue as well as reduce the load on osc2mqtt for my application.

**Comment by SpotlightKid** [comment]
Fixed in 91b2227.
